apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: travel-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: local