# Generated by Django 5.1.1 on 2024-12-24 19:10

import django.db.models.deletion
import src.models.application_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_applicationtour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=90)),
                ('report_type', models.CharField(choices=[('day', 'За день'), ('week', 'За неделю'), ('month', 'За месяц')], max_length=40)),
                ('file', models.FileField(editable=False, null=True, upload_to='reports/')),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='applicationtour',
            options={'verbose_name': 'Заявка на тур', 'verbose_name_plural': 'Заявки на туры'},
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='applicationtour',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in-process', 'В обработке'), ('processed', 'Обработан'), ('done', 'Готово')], default='new', max_length=40),
        ),
        migrations.AlterField(
            model_name='applicationtour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.tour'),
        ),
        migrations.CreateModel(
            name='ProgramTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=60)),
                ('attraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.attraction')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(validators=[src.models.application_models.max_value_validator])),
                ('message', models.TextField()),
                ('application_tour', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='src.applicationtour')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
            },
        ),
    ]
