# Generated by Django 5.2.12 on 2026-04-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_report_alter_applicationtour_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(editable=False, null=True, upload_to='reports/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('day', 'За день'), ('week', 'За неделю'), ('month', 'За месяц')], max_length=40, verbose_name='Отчет за'),
        ),
    ]
